name: fyp
description: An E-commerce plant app.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  curved_navigation_bar: ^1.0.3
  provider: ^6.0.5
  smooth_page_indicator: ^1.1.0
  firebase_core: ^2.10.0
  firebase_auth: ^4.4.2
  lottie: ^2.3.2
  connectivity_plus: ^3.0.6
  cloud_firestore: ^4.6.0
  shared_preferences: ^2.1.0
  image_picker: ^0.8.7+4
  intl: ^0.17.0
  flutter_dotenv: ^5.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    # - .env
  fonts:
    - family: Quicksand
      fonts:
        - asset: assets/fonts/Quicksand-Regular.ttf
        - asset: assets/fonts/Quicksand-Bold.ttf
        - asset: assets/fonts/Quicksand-Medium.ttf
    - family: Sora
      fonts:
        - asset: assets/fonts/Sora-Medium.ttf
        - asset: assets/fonts/Sora-Regular.ttf
