// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDbJuArG-4OTWlkffElGeyZm5Hu-lyJeA8',
    appId: '1:463043424929:web:e7322d012f67cbbdd2f6e0',
    messagingSenderId: '463043424929',
    projectId: 'final-year-project-3a10f',
    authDomain: 'final-year-project-3a10f.firebaseapp.com',
    storageBucket: 'final-year-project-3a10f.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAMZzxy9k6N4Y-_FlusGygudipM7zV63vc',
    appId: '1:463043424929:android:06b57a30fffc370ad2f6e0',
    messagingSenderId: '463043424929',
    projectId: 'final-year-project-3a10f',
    storageBucket: 'final-year-project-3a10f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB5Nw02ubGkdE6nYEoaBHzufv8EbtodnLU',
    appId: '1:463043424929:ios:050feb815e6fbc3fd2f6e0',
    messagingSenderId: '463043424929',
    projectId: 'final-year-project-3a10f',
    storageBucket: 'final-year-project-3a10f.appspot.com',
    iosClientId: '463043424929-r5bc2kct464si697vsemu9bmlge2if51.apps.googleusercontent.com',
    iosBundleId: 'com.example.fyp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB5Nw02ubGkdE6nYEoaBHzufv8EbtodnLU',
    appId: '1:463043424929:ios:050feb815e6fbc3fd2f6e0',
    messagingSenderId: '463043424929',
    projectId: 'final-year-project-3a10f',
    storageBucket: 'final-year-project-3a10f.appspot.com',
    iosClientId: '463043424929-r5bc2kct464si697vsemu9bmlge2if51.apps.googleusercontent.com',
    iosBundleId: 'com.example.fyp',
  );
}
